/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about': RouteRecordInfo<
      '/about',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/users': RouteRecordInfo<
      '/admin/users',
      '/admin/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/forgot-password': RouteRecordInfo<
      '/auth/forgot-password',
      '/auth/forgot-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/login': RouteRecordInfo<
      '/auth/login',
      '/auth/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/profile': RouteRecordInfo<
      '/auth/profile',
      '/auth/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/register': RouteRecordInfo<
      '/auth/register',
      '/auth/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/reset-password': RouteRecordInfo<
      '/auth/reset-password',
      '/auth/reset-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/verify': RouteRecordInfo<
      '/auth/verify',
      '/auth/verify',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/components': RouteRecordInfo<
      '/components',
      '/components',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/customer/home': RouteRecordInfo<
      '/customer/home',
      '/customer/home',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard': RouteRecordInfo<
      '/dashboard',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/foundation': RouteRecordInfo<
      '/foundation',
      '/foundation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'resources/js/app/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'resources/js/app/pages/about.vue': {
      routes:
        | '/about'
      views:
        | never
    }
    'resources/js/app/pages/admin/users.vue': {
      routes:
        | '/admin/users'
      views:
        | never
    }
    'resources/js/app/pages/auth/forgot-password.vue': {
      routes:
        | '/auth/forgot-password'
      views:
        | never
    }
    'resources/js/app/pages/auth/login.vue': {
      routes:
        | '/auth/login'
      views:
        | never
    }
    'resources/js/app/pages/auth/profile.vue': {
      routes:
        | '/auth/profile'
      views:
        | never
    }
    'resources/js/app/pages/auth/register.vue': {
      routes:
        | '/auth/register'
      views:
        | never
    }
    'resources/js/app/pages/auth/reset-password.vue': {
      routes:
        | '/auth/reset-password'
      views:
        | never
    }
    'resources/js/app/pages/auth/verify.vue': {
      routes:
        | '/auth/verify'
      views:
        | never
    }
    'resources/js/app/pages/components.vue': {
      routes:
        | '/components'
      views:
        | never
    }
    'resources/js/app/pages/customer/home.vue': {
      routes:
        | '/customer/home'
      views:
        | never
    }
    'resources/js/app/pages/dashboard.vue': {
      routes:
        | '/dashboard'
      views:
        | never
    }
    'resources/js/app/pages/foundation.vue': {
      routes:
        | '/foundation'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
